routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('logica', function () {
    return view('logica');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
/* Create routes to Client Management */
Route::resource('client', 'ClientController');
Route::get('client/destroy/{id}', ['as' => 'client/destroy', 'uses' => 'ClientController@destroy']);
/* Create routes to Client Management */
Route::resource('car', 'CarController');
Route::get('car/destroy/{id}', ['as' => 'car/destroy', 'uses' => 'CarController@destroy']);

app/Models/Car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $table = 'cars';
    protected $fillable = ['licensePlate', 'typeCar', 'mark', 'description', 'client_id'];
    protected $guarded = ['id'];
}

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'clients';
    protected $fillable = ['name', 'numberDocument', 'description'];
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// Import Model of Car
use App\Models\Car as Car;
// Import Model of Client
use App\Models\Client as Client;


class CarController extends Controller
{
    //Method to create
    public function store(Request $request)
    {
    	$car = new Car;
    	$car->create($request->all());
    	return redirect('car');
    }
    //Method to update
    public function update($id, Request $request)
    {
        $car = Car::find($id);
        $car->licensePlate = $request->licensePlate;
        $car->typeCar = $request->typeCar;
        $car->mark = $request->mark;
        $car->description = $request->description;
        $car->client_id = $request->client_id;
        $car->save();
        return redirect('car');
    }
    //Method to redirect to view create
    public function create(){
        $clients = Client::all();
    	return \View::make('cars/new', compact('clients'));
    }
    //Method to redirect to view list
    public function index(){
        $cars = Car::all();
        return \View::make('cars/list', compact('cars'));
    }
    //Method to redirect to view update with the information of car
    public function edit($id){
        $car = Car::find($id);
        $clients = Client::all();
        return \View::make('cars/update', compact('car', 'clients'));
    }
    //Method to delete
    public function destroy($id){
        $car = Car::find($id);
        $car->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
// Import Model of Client
use App\Models\Client as Client;

class ClientController extends Controller
{
    //Method to create
    public function store(Request $request)
    {
    	$client = new Client;
    	$client->create($request->all());
    	return redirect('client');
    }
    //Method to update
    public function update($id, Request $request)
    {
        $client = Client::find($id);
        $client->name = $request->name;
        $client->numberDocument = $request->numberDocument;
        $client->description = $request->description;
        $client->save();
        return redirect('client');
    }
    //Method to redirect to view create
    public function create(){
    	return \View::make('clients/new');
    }
    //Method to redirect to view list
    public function index(){
        $clients = Client::all();
        return \View::make('clients/list', compact('clients'));
    }
    //Method to redirect to view update with the information of client
    public function edit($id){
        $client = Client::find($id);
        return \View::make('clients/update', compact('client'));
    }
    //Method to delete
    public function destroy($id){
        $client = Client::find($id);
        $client->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/cars/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12 newSect text-center">
				<h3>Listado de vehículos</h3><br>
				<a href="{{ route('car.create') }}" class="btn btn-primary text-light"><md-icon class="text-light">add_box</md-icon> Nuevo vehículo</a>
			</article>
			<article class="col-md-12">
				<div class="table-responsive text-center">
					<table class="table table-striped table-bordered table-hover" id="table_car">
						<thead>
							<tr>
								<th>Placa</th>
								<th>Marca</th>
								<th>Tipo</th>
								<th>Descripción</th>
								<th>Acción</th>
							</tr>
						</thead>
						<tbody>
							@foreach($cars as $car)
								<tr>
									<td><p class="mayus">{{ $car->licensePlate }}</p></td>
									<td><p>{{ $car->mark }}</p></td>
									<td><p>{{ $car->typeCar }}</p></td>
									<td><p>{{ $car->description }}</p></td>	
									<td>
										<a href="{{ route('car.edit', ['id' => $car->id]) }}" class="btn btn-info text-light"><md-icon class="text-light">create</md-icon> Editar</a>
										<a href="{{ route('car/destroy', ['id' => $car->id]) }}" class="btn btn-danger text-light"><md-icon class="text-light">delete_forever</md-icon> Eliminar</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</article>
		</div>
	</section>
@endsection()

resources/views/cars/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-3"></article>
			<article class="col-md-6 text-center">
				<div class="newSect"><h3>Creación de vehículos</h3></div>
				{!! Form::model($clients ,['route' => 'car.store', 'method' => 'POST']) !!}
					<div class="form-group">
						<label>Placa del vehículo</label>
						<input type="text" name="licensePlate" class="form-control" id="name" required maxlength="6">
					</div>
					<div class="form-group">
						<label>Tipo del vehículo</label>
						<select class="form-control" name="typeCar" id="typeCar" required>
							<option selected>Seleccione...</option>
							<option value="Automóvil">Automóvil</option>
							<option value="Autobus">Autobus</option>
							<option value="Camion">Camion</option>
							<option value="Camioneta">Camioneta</option>
							<option value="Furgón">Furgón</option>
						</select>
					</div>
					<div class="form-group">
						<label>Marca del vehículo</label>
						<input type="text" class="form-control" name="mark" id="mark" required maxlength="100">
					</div>
					<div class="form-group">
						<label>Propietario del vehículo</label>
						<select class="form-control" name="client_id" id="client_id" required>
							<option selected>Seleccione...</option>
							@foreach($clients as $client)
								<option value="{{ $client->id }}">{{ $client->id }} - {{ $client->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<textarea name="description" class="form-control" id="description" required maxlength="250"></textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success"><md-icon class="text-light">save</md-icon>  Guardar información</button>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-3"></article>
		</div>
	</section>
@endsection()

resources/views/cars/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-3"></article>
			<article class="col-md-6 text-center">
				<div class="newSect"><h3>Actualización de vehículos</h3></div>
				{!! Form::model($car ,['route' => ['car.update', $car->id], 'method' => 'PUT']) !!}
					<div class="form-group">
						<label>Placa del vehículo</label>
						<input type="text" name="licensePlate" class="form-control" id="name" required maxlength="6" value="{{ $car->licensePlate }}">
					</div>
					<div class="form-group">
						<label>Tipo del vehículo</label>
						<select class="form-control" name="typeCar" id="typeCar" required>
							<option selected value="{{ $car->typeCar }}">{{ $car->typeCar }}</option>
							<option value="Automóvil">Automóvil</option>
							<option value="Autobus">Autobus</option>
							<option value="Camion">Camion</option>
							<option value="Camioneta">Camioneta</option>
							<option value="Furgón">Furgón</option>
						</select>
					</div>
					<div class="form-group">
						<label>Marca del vehículo</label>
						<input type="text" class="form-control" name="mark" id="mark" required maxlength="100" value="{{ $car->mark }}">
					</div>
					<div class="form-group">
						<label>Propietario del vehículo</label>
						<select class="form-control" name="client_id" id="client_id" required>
							<option selected value="{{ $car->client_id }}">{{ $car->client_id }}</option>
							@foreach($clients as $client)
								<option value="{{ $client->id }}">{{ $client->id }} - {{ $client->name }}</option>
							@endforeach
						</select>
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<textarea name="description" class="form-control" id="description" required maxlength="250">{{ $car->description }}</textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success"><md-icon class="text-light">save</md-icon> Guardar información</button>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-3"></article>
		</div>
	</section>
@endsection()

resources/views/clients/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row text-center">
			<article class="col-md-12 newSect text-center">
				<h3>Listado de clientes</h3><br>	
				<a href="{{ route('client.create') }}" class="btn btn-primary text-light"><md-icon class="text-light">add_box</md-icon> Nuevo Cliente</a>
			</article>
			<article class="col-md-12">
				<div class="table-responsive text-center">
					<table class="table table-striped table-bordered table-hover" id="table_client">
						<thead>
							<tr>
								<th>Nombre</th>
								<th>Número de documento</th>
								<th>Descripción</th>
								<th>Acción</th>
							</tr>
						</thead>
						<tbody>
							@foreach($clients as $client)
								<tr>
									<td><p>{{ $client->name }}</p></td>
									<td><p>{{ $client->numberDocument }}</p></td>
									<td><p>{{ $client->description }}</p></td>	
									<td>
										<a href="{{ route('client.edit', ['id' => $client->id]) }}" class="btn btn-info text-light"><md-icon class="text-light">create</md-icon> Editar</a>
										<a href="{{ route('client/destroy', ['id' => $client->id]) }}" class="btn btn-danger text-light"><md-icon class="text-light">delete_forever</md-icon> Eliminar</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</article>
		</div>
	</section>
@endsection()

resources/views/clients/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-3"></article>
			<article class="col-md-6 text-center">
				<div class="newSect"><h3>Creación de clientes</h3></div>
				{!! Form::open(['route' => 'client.store', 'method' => 'POST']) !!}
					<div class="form-group">
						<label>Nombre del cliente</label>
						<input type="text" name="name" class="form-control" id="name" required maxlength="100">
					</div>
					<div class="form-group">
						<label>Número de documento</label>
						<input type="tel" name="numberDocument" class="form-control" id="numberDocument" required maxlength="15" minlength="5">
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<textarea name="description" class="form-control" id="description" required maxlength="250"></textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success"><md-icon class="text-light">save</md-icon> Guardar información</button>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-3"></article>
		</div>
	</section>
@endsection()

resources/views/clients/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-3"></article>
			<article class="col-md-6 text-center">
				<div class="newSect"><h3>Actualizacion de clientes</h3></div>
				{!! Form::model($client, ['route' => ['client.update', $client->id], 'method' => 'PUT']) !!}
					<div class="form-group">
						<label>Nombre del cliente</label>
						<input type="text" name="name" class="form-control" id="name" required maxlength="100" value="{{ $client->name }}">
					</div>
					<div class="form-group">
						<label>Número de documento</label>
						<input type="tel" name="numberDocument" class="form-control" id="numberDocument" required maxlength="15" minlength="5" value="{{ $client->numberDocument }}">
					</div>
					<div class="form-group">
						<label>Descripción</label>
						<textarea name="description" class="form-control" id="description" required maxlength="250">{{ $client->description }}</textarea>
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success"><md-icon class="text-light">save</md-icon> Guardar información</button>
					</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-3"></article>
		</div>
	</section>
@endsection()

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <br>
    <md-empty-state
        md-rounded
        md-icon="verified"
        md-label="¡Hola {{ Auth::user()->name }}!"
        md-description="Selecciona una de las opciones del menú para iniciar con la interacción.">
    </md-empty-state>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Prueba Tecnica | GradiWeb</title>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,500,700,400italic|Material+Icons">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css"> 
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
    <style lang="scss" scoped>
  .md-app {
    min-height: 350px;
    border: 1px solid rgba(#000, .12);
  }

   // Demo purposes only
  .md-drawer {
    width: 230px;
    max-width: calc(100vw - 125px);
  }
</style>
</head>
<body>
    <div class="jm-loadingpage"></div>
    <div id="app">
        <!-- Authentication Links -->
        @guest
            <app :login="false"></app>
        @else
            <app :login="true"></app>
        @endguest
        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script type="text/javascript">
       
    </script>
</body>
</html>

resources/views/logica.blade.php
@extends('layouts.app')

@section('content')
<logica></logica>
@endsection